<?php

/**
 * Author: Rowan Burgess
 */
class Bzaikia_Api_Model_Api2_Cart_Clear_Rest_Guest_V1 extends Bzaikia_Api_Model_Api2_Cart_Clear
{

    const ERROR_NO_ITEM_IN_CART = 'There is no item left on the cart';

    /**
     * @param array $filteredData
     */
    public function _create(array $filteredData)
    {
        if ($this->_isLogEnable()) {
            $this->_log($filteredData);
        }
        $this->setCustomerId($filteredData[self::PARAM_USER_ID]);
        $userId = $this->getCustomerId();

        if ($this->_validateAuthorization($userId) && $this->_validate($filteredData)) {
            try {
                $quote = $this->_getQuote($userId);
                $quote->removeAllItems();
                $quote->collectTotals();
                $quote->save();
                $this->getResponse()->setHttpResponseCode(Bzaikia_Api_Helper_Data::SUCCESSFUL_CODE);
            } catch (Exception $e) {
                $this->_message = $e->getMessage();
                $this->getResponse()->setHttpResponseCode(Bzaikia_Api_Helper_Data::SERVER_ERROR_CODE);
            }
        }

        if ($this->_message) {
            $this->getResponse()->setBody($this->_message);
        }
    }

    /**
     * @param $params
     * @return bool
     */
    protected function _validate($params)
    {
        return parent::_validate($params); // TODO: Change the autogenerated stub
    }
}